# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from shutterstock_python_sdk import Shutterstock

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        shutterstock = Shutterstock(
        
            username = 'YOUR_USERNAME',
            password = 'YOUR_PASSWORD',
        
            client_id = 'YOUR_CLIENT_ID',
            client_secret = 'YOUR_CLIENT_SECRET',
        )
        self.assertIsNotNone(shutterstock)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
