# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from shutterstock_python_sdk.paths.v2_audio_collections_id_items.post import AddTracksToCollection
from shutterstock_python_sdk.paths.v2_audio_collections.post import CreateCollections
from shutterstock_python_sdk.paths.v2_audio_collections_id.delete import DeleteCollection
from shutterstock_python_sdk.paths.v2_audio_collections_id.get import GetCollectionDetails
from shutterstock_python_sdk.paths.v2_audio_id.get import GetTrackDetails
from shutterstock_python_sdk.paths.v2_audio_licenses.post import LicenseTracks
from shutterstock_python_sdk.paths.v2_audio_licenses.get import ListAudioLicenses
from shutterstock_python_sdk.paths.v2_audio_collections_id_items.get import ListCollectionItems
from shutterstock_python_sdk.paths.v2_audio_collections.get import ListCollections
from shutterstock_python_sdk.paths.v2_audio_genres.get import ListGenres
from shutterstock_python_sdk.paths.v2_audio_instruments.get import ListInstruments
from shutterstock_python_sdk.paths.v2_audio_moods.get import ListMoods
from shutterstock_python_sdk.paths.v2_audio.get import ListTracks
from shutterstock_python_sdk.paths.v2_audio_licenses_id_downloads.post import RedownloadTracks
from shutterstock_python_sdk.paths.v2_audio_collections_id_items.delete import RemoveTracksFromCollection
from shutterstock_python_sdk.paths.v2_audio_search.get import SearchTracks
from shutterstock_python_sdk.paths.v2_audio_collections_id.post import SetCollectionName
from shutterstock_python_sdk.apis.tags.audio_api_raw import AudioApiRaw


class AudioApi(
    AddTracksToCollection,
    CreateCollections,
    DeleteCollection,
    GetCollectionDetails,
    GetTrackDetails,
    LicenseTracks,
    ListAudioLicenses,
    ListCollectionItems,
    ListCollections,
    ListGenres,
    ListInstruments,
    ListMoods,
    ListTracks,
    RedownloadTracks,
    RemoveTracksFromCollection,
    SearchTracks,
    SetCollectionName,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AudioApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AudioApiRaw(api_client)
