# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from shutterstock_python_sdk.paths.v2_cv_similar_images.get import ListSimilarImagesRaw
from shutterstock_python_sdk.paths.v2_cv_similar_videos.get import ListSimilarVideosRaw
from shutterstock_python_sdk.paths.v2_cv_keywords.get import ListSuggestedKeywordsRaw
from shutterstock_python_sdk.paths.v2_cv_images.post import UploadImageRaw
from shutterstock_python_sdk.paths.v2_images.post import UploadImageEphemeralRaw


class ComputerVisionApiRaw(
    ListSimilarImagesRaw,
    ListSimilarVideosRaw,
    ListSuggestedKeywordsRaw,
    UploadImageRaw,
    UploadImageEphemeralRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
