# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from shutterstock_python_sdk.paths.v2_contributors_contributor_id_collections_id.get import GetCollectionDetailsRaw
from shutterstock_python_sdk.paths.v2_contributors_contributor_id_collections_id_items.get import GetCollectionItemsRaw
from shutterstock_python_sdk.paths.v2_contributors_contributor_id.get import GetDetailsRaw
from shutterstock_python_sdk.paths.v2_contributors.get import GetDetailsMultipleRaw
from shutterstock_python_sdk.paths.v2_contributors_contributor_id_collections.get import ListCollectionsRaw


class ContributorsApiRaw(
    GetCollectionDetailsRaw,
    GetCollectionItemsRaw,
    GetDetailsRaw,
    GetDetailsMultipleRaw,
    ListCollectionsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
