# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from shutterstock_python_sdk.paths.v2_editorial_videos_id.get import GetContentDetailsRaw
from shutterstock_python_sdk.paths.v2_editorial_videos_licenses.post import LicenseVideosRaw
from shutterstock_python_sdk.paths.v2_editorial_videos_categories.get import ListVideoCategoriesRaw
from shutterstock_python_sdk.paths.v2_editorial_videos_licenses.get import ListVideoLicensesRaw
from shutterstock_python_sdk.paths.v2_editorial_videos_search.get import SearchVideoContentRaw


class EditorialVideoApiRaw(
    GetContentDetailsRaw,
    LicenseVideosRaw,
    ListVideoCategoriesRaw,
    ListVideoLicensesRaw,
    SearchVideoContentRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
