# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from shutterstock_python_sdk.paths.v2_editorial_id.get import GetDetails
from shutterstock_python_sdk.paths.v2_editorial_images_id.get import GetImageDetails
from shutterstock_python_sdk.paths.v2_editorial_images_livefeeds_id.get import GetLivefeedImages
from shutterstock_python_sdk.paths.v2_editorial_images_livefeeds_id_items.get import GetLivefeedItems
from shutterstock_python_sdk.paths.v2_editorial_livefeeds_id.get import GetLivefeedItems0
from shutterstock_python_sdk.paths.v2_editorial_livefeeds_id_items.get import GetLivefeedItems1
from shutterstock_python_sdk.paths.v2_editorial_livefeeds.get import GetLivefeedList
from shutterstock_python_sdk.paths.v2_editorial_images_licenses.post import LicenseContent
from shutterstock_python_sdk.paths.v2_editorial_licenses.post import LicenseContent0
from shutterstock_python_sdk.paths.v2_editorial_categories.get import ListCategories
from shutterstock_python_sdk.paths.v2_editorial_images_categories.get import ListCategories0
from shutterstock_python_sdk.paths.v2_editorial_images_licenses.get import ListLicenses
from shutterstock_python_sdk.paths.v2_editorial_images_livefeeds.get import ListLivefeedImages
from shutterstock_python_sdk.paths.v2_editorial_images_updated.get import ListUpdatedContent
from shutterstock_python_sdk.paths.v2_editorial_updated.get import ListUpdatedContent0
from shutterstock_python_sdk.paths.v2_editorial_images_search.get import Search
from shutterstock_python_sdk.paths.v2_editorial_search.get import SearchContent
from shutterstock_python_sdk.apis.tags.editorial_images_api_raw import EditorialImagesApiRaw


class EditorialImagesApi(
    GetDetails,
    GetImageDetails,
    GetLivefeedImages,
    GetLivefeedItems,
    GetLivefeedItems0,
    GetLivefeedItems1,
    GetLivefeedList,
    LicenseContent,
    LicenseContent0,
    ListCategories,
    ListCategories0,
    ListLicenses,
    ListLivefeedImages,
    ListUpdatedContent,
    ListUpdatedContent0,
    Search,
    SearchContent,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EditorialImagesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EditorialImagesApiRaw(api_client)
