# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from shutterstock_python_sdk.paths.v2_editorial_videos_id.get import GetContentDetails
from shutterstock_python_sdk.paths.v2_editorial_videos_licenses.post import LicenseVideos
from shutterstock_python_sdk.paths.v2_editorial_videos_categories.get import ListVideoCategories
from shutterstock_python_sdk.paths.v2_editorial_videos_licenses.get import ListVideoLicenses
from shutterstock_python_sdk.paths.v2_editorial_videos_search.get import SearchVideoContent
from shutterstock_python_sdk.apis.tags.editorial_video_api_raw import EditorialVideoApiRaw


class EditorialVideoApi(
    GetContentDetails,
    LicenseVideos,
    ListVideoCategories,
    ListVideoLicenses,
    SearchVideoContent,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EditorialVideoApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EditorialVideoApiRaw(api_client)
