# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from shutterstock_python_sdk.paths.v2_sfx_id.get import GetDetails
from shutterstock_python_sdk.paths.v2_sfx_licenses.post import LicenseAssets
from shutterstock_python_sdk.paths.v2_sfx.get import ListDetails
from shutterstock_python_sdk.paths.v2_sfx_licenses.get import ListLicenses
from shutterstock_python_sdk.paths.v2_sfx_licenses_id_downloads.post import RedownloadLicenses
from shutterstock_python_sdk.paths.v2_sfx_search.get import SearchSoundEffects
from shutterstock_python_sdk.apis.tags.sound_effects_api_raw import SoundEffectsApiRaw


class SoundEffectsApi(
    GetDetails,
    LicenseAssets,
    ListDetails,
    ListLicenses,
    RedownloadLicenses,
    SearchSoundEffects,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SoundEffectsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SoundEffectsApiRaw(api_client)
