# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

import unittest

import shutterstock_python_sdk
from shutterstock_python_sdk.model.oauth_get_user_access_token_request import OauthGetUserAccessTokenRequest
from shutterstock_python_sdk import configuration


class TestOauthGetUserAccessTokenRequest(unittest.TestCase):
    """OauthGetUserAccessTokenRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
