# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

import unittest

import shutterstock_python_sdk
from shutterstock_python_sdk.model.collection_item_data_list import CollectionItemDataList
from shutterstock_python_sdk import configuration


class TestCollectionItemDataList(unittest.TestCase):
    """CollectionItemDataList unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
