# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from shutterstock_python_sdk.type.access_token_details_scopes import AccessTokenDetailsScopes

class RequiredAccessTokenDetails(TypedDict):
    pass

class OptionalAccessTokenDetails(TypedDict, total=False):
    # Client ID that is associated with the user
    client_id: str

    # Contributor ID that is associated with the user
    contributor_id: str

    # Customer ID that is associated with the user
    customer_id: str

    # Number of seconds until the access token expires; no expiration if this value is null
    expires_in: int

    # Organization ID that is associated with the user
    organization_id: str

    # Type of access token
    realm: str

    scopes: AccessTokenDetailsScopes

    # User ID that is associated with the user
    user_id: str

    # User name that is associated with the user
    username: str

class AccessTokenDetails(RequiredAccessTokenDetails, OptionalAccessTokenDetails):
    pass
