# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAllotment(TypedDict):
    pass

class OptionalAllotment(TypedDict, total=False):
    # Number of credits remaining in the subscription
    downloads_left: int

    # Total number of credits available to this subscription
    downloads_limit: int

    # Date the subscription ends
    end_time: datetime

    # Date the subscription started
    start_time: datetime

class Allotment(RequiredAllotment, OptionalAllotment):
    pass
