# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAudioUrl(TypedDict):
    # URL that can be used to download the unwatermarked, licensed asset
    url: str

class OptionalAudioUrl(TypedDict, total=False):
    # URL that can be used to download the .zip file containing shorts, loops, and stems
    shorts_loops_stems: str

class AudioUrl(RequiredAudioUrl, OptionalAudioUrl):
    pass
