# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from shutterstock_python_sdk.type.contributor_profile import ContributorProfile
from shutterstock_python_sdk.type.error import Error

class RequiredContributorProfileDataList(TypedDict):
    pass

class OptionalContributorProfileDataList(TypedDict, total=False):
    # Conributor profiles
    data: typing.List[ContributorProfile]

    # Error list; appears only if there was an error
    errors: typing.List[Error]

    # Error message
    message: str

    # Page of response
    page: int

    # Number of contributors per page
    per_page: int

    # Total count of contributors for this request
    total_count: int

class ContributorProfileDataList(RequiredContributorProfileDataList, OptionalContributorProfileDataList):
    pass
