# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDownloadHistoryFormatDetails(TypedDict):
    pass

class OptionalDownloadHistoryFormatDetails(TypedDict, total=False):
    # The format of the downloaded media
    format: str

    # The size of the downloaded media
    size: str

class DownloadHistoryFormatDetails(RequiredDownloadHistoryFormatDetails, OptionalDownloadHistoryFormatDetails):
    pass
