# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from shutterstock_python_sdk.type.download_history_media_details import DownloadHistoryMediaDetails
from shutterstock_python_sdk.type.download_history_revshare_details import DownloadHistoryRevshareDetails
from shutterstock_python_sdk.type.download_history_user_details import DownloadHistoryUserDetails

class RequiredDownloadHistory(TypedDict):
    # Date the media was downloaded the first time
    download_time: datetime

    # ID of the download
    id: str

    # The name of the license of this download
    license: str

class OptionalDownloadHistory(TypedDict, total=False):
    audio: DownloadHistoryMediaDetails

    image: DownloadHistoryMediaDetails

    # Specifies if the media is downloadable via its respective downloads endpoint
    is_downloadable: bool

    # The metadata that was passed in the original licensing request
    metadata: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    revshare: DownloadHistoryRevshareDetails

    # ID of the subscription used to perform this download
    subscription_id: str

    user: DownloadHistoryUserDetails

    video: DownloadHistoryMediaDetails

class DownloadHistory(RequiredDownloadHistory, OptionalDownloadHistory):
    pass
