# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from shutterstock_python_sdk.type.video_preview_url import VideoPreviewUrl
from shutterstock_python_sdk.type.video_size_details import VideoSizeDetails

class RequiredEditorialVideoAssets(TypedDict):
    pass

class OptionalEditorialVideoAssets(TypedDict, total=False):
    original: VideoSizeDetails

    preview_mp4: VideoPreviewUrl

    preview_webm: VideoPreviewUrl

    thumb_jpg: VideoPreviewUrl

class EditorialVideoAssets(RequiredEditorialVideoAssets, OptionalEditorialVideoAssets):
    pass
