# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from shutterstock_python_sdk.type.image_size_details import ImageSizeDetails
from shutterstock_python_sdk.type.thumbnail import Thumbnail

class RequiredImageAssets(TypedDict):
    pass

class OptionalImageAssets(TypedDict, total=False):
    huge_jpg: ImageSizeDetails

    huge_thumb: Thumbnail

    large_thumb: Thumbnail

    medium_jpg: ImageSizeDetails

    preview: Thumbnail

    preview_1000: Thumbnail

    preview_1500: Thumbnail

    small_jpg: ImageSizeDetails

    small_thumb: Thumbnail

    supersize_jpg: ImageSizeDetails

    vector_eps: ImageSizeDetails

class ImageAssets(RequiredImageAssets, OptionalImageAssets):
    pass
