# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredImageSizeDetails(TypedDict):
    pass

class OptionalImageSizeDetails(TypedDict, total=False):
    # Display name of this image size
    display_name: str

    dpi: int

    # File size (in bytes) of this image size
    file_size: int

    # Format of this image size
    format: str

    # Height of this image size
    height: int

    # Whether or not this image can be licensed in this image size
    is_licensable: bool

    # Width of this image size
    width: int

class ImageSizeDetails(RequiredImageSizeDetails, OptionalImageSizeDetails):
    pass
