# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from shutterstock_python_sdk.type.error import Error

class RequiredKeywordDataList(TypedDict):
    pass

class OptionalKeywordDataList(TypedDict, total=False):
    # Keywords
    data: typing.List[str]

    # Error list; appears only if there was an error
    errors: typing.List[Error]

    # Server-generated message, if any
    message: str

class KeywordDataList(RequiredKeywordDataList, OptionalKeywordDataList):
    pass
