# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from shutterstock_python_sdk.type.cookie import Cookie
from shutterstock_python_sdk.type.license_request_metadata import LicenseRequestMetadata

class RequiredLicenseImageVector(TypedDict):
    # Image ID
    image_id: str

class OptionalLicenseImageVector(TypedDict, total=False):
    auth_cookie: Cookie

    # Set to true to acknowledge the editorial agreement
    editorial_acknowledgement: bool

    # (Deprecated) Image format to download
    format: str

    metadata: LicenseRequestMetadata

    # For revenue-sharing transactions, the final cost to the end customer as a floating-point number in the transaction currency, such as 12.34
    price: typing.Union[int, float]

    # ID of the search that led to this licensing transaction
    search_id: str

    # (Deprecated)
    show_modal: bool

    # Image size to download
    size: str

    # ID of the subscription to use for the download.
    subscription_id: str

    # (Deprecated)
    verification_code: str

class LicenseImageVector(RequiredLicenseImageVector, OptionalLicenseImageVector):
    pass
