# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from shutterstock_python_sdk.type.license_request_metadata import LicenseRequestMetadata

class RequiredLicenseEditorialVideoContent(TypedDict):
    # Editorial ID
    editorial_id: str

    # License agreement to use for licensing
    license: str

class OptionalLicenseEditorialVideoContent(TypedDict, total=False):
    metadata: LicenseRequestMetadata

    # Asset size to download
    size: str

class LicenseEditorialVideoContent(RequiredLicenseEditorialVideoContent, OptionalLicenseEditorialVideoContent):
    pass
