# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredOauthAccessTokenResponse(TypedDict):
    # Access token that can be used for future requests
    access_token: str

    # Type of token
    token_type: str

class OptionalOauthAccessTokenResponse(TypedDict, total=False):
    # Number of seconds before token expires, only present for expiring tokens
    expires_in: int

    # A refresh token that can be used to renew the access_token when it expires, only present for expiring tokens
    refresh_token: str

    # Metadata about the access_token, only present for expiring tokens
    user_token: str

class OauthAccessTokenResponse(RequiredOauthAccessTokenResponse, OptionalOauthAccessTokenResponse):
    pass
