# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from shutterstock_python_sdk.type.language import Language
from shutterstock_python_sdk.type.search_image_contributor import SearchImageContributor
from shutterstock_python_sdk.type.search_image_image_type import SearchImageImageType
from shutterstock_python_sdk.type.search_image_license import SearchImageLicense
from shutterstock_python_sdk.type.search_image_model import SearchImageModel
from shutterstock_python_sdk.type.search_image_people_ethnicity import SearchImagePeopleEthnicity

class RequiredSearchImage(TypedDict):
    pass

class OptionalSearchImage(TypedDict, total=False):
    # Show images added on the specified date
    added_date: date

    # Show images added before the specified date
    added_date_end: date

    # Show images added on or after the specified date
    added_date_start: date

    # Show images with the specified aspect ratio, using a positive decimal of the width divided by the height, such as 1.7778 for a 16:9 image
    aspect_ratio: typing.Union[int, float]

    # Show images with the specified aspect ratio or lower, using a positive decimal of the width divided by the height, such as 1.7778 for a 16:9 image
    aspect_ratio_max: typing.Union[int, float]

    # Show images with the specified aspect ratio or higher, using a positive decimal of the width divided by the height, such as 1.7778 for a 16:9 image
    aspect_ratio_min: typing.Union[int, float]

    # Show only authentic images
    authentic: bool

    # Show images with the specified Shutterstock-defined category; specify a category name or ID
    category: str

    # Specify either a hexadecimal color in the format '4F21EA' or 'grayscale'; the API returns images that use similar colors
    color: str

    contributor: SearchImageContributor

    # Show images from contributors in one or more specified countries, or start with NOT to exclude a country from the search
    contributor_country: typing.Union[typing.List[str], typing.List[str]]

    # Fields to display in the response; see the documentation for the fields parameter in the overview section
    fields: str

    # (Deprecated; use height_from and height_to instead) Show images with the specified height
    height: int

    # Show images with the specified height or larger, in pixels
    height_from: int

    # Show images with the specified height or smaller, in pixels
    height_to: int

    image_type: SearchImageImageType

    # Hide results with potentially unsafe keywords
    keyword_safe_search: bool

    language: Language

    license: SearchImageLicense

    model: SearchImageModel

    # Show image results with horizontal or vertical orientation
    orientation: str

    # Page number
    page: int

    # Show images that feature people of the specified age category
    people_age: str

    people_ethnicity: SearchImagePeopleEthnicity

    # Show images with people of the specified gender
    people_gender: str

    # Show images of people with a signed model release
    people_model_released: bool

    # Show images with the specified number of people
    people_number: int

    # Number of results per page
    per_page: int

    # One or more search terms separated by spaces; you can use NOT to filter out images that match a term
    query: str

    # Raise or lower search result rankings based on the result's relevance to a specified region; you can provide a country code or an IP address from which the API infers a country
    region: typing.Union[str, str]

    # Enable or disable safe search
    safe: bool

    # Sort by
    sort: str

    # Spellcheck the search query and return results on suggested spellings
    spellcheck_query: bool

    # Amount of detail to render in the response
    view: str

    # (Deprecated; use width_from and width_to instead) Show images with the specified width
    width: int

    # Show images with the specified width or larger, in pixels
    width_from: int

    # Show images with the specified width or smaller, in pixels
    width_to: int

class SearchImage(RequiredSearchImage, OptionalSearchImage):
    pass
