# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from shutterstock_python_sdk.type.contributor import Contributor
from shutterstock_python_sdk.type.sfx_assets import SFXAssets
from shutterstock_python_sdk.type.sfx_keywords import SFXKeywords
from shutterstock_python_sdk.type.sfx_releases import SFXReleases

class RequiredSFX(TypedDict):
    contributor: Contributor

    # Shutterstock ID of this sound effect
    id: str

    # Media type of this track; should always be \"sfx\"
    media_type: str

class OptionalSFX(TypedDict, total=False):
    # Title of this sound effect
    title: str

    # Description of this sound effect
    description: str

    # Date this sound effect was added to the Shutterstock library
    added_date: date

    # Affiliate referral link; appears only for registered affiliate partners
    affiliate_url: str

    # Artist of the sound effect
    artist: str

    assets: SFXAssets

    # Duration of this sound effect in seconds
    duration: typing.Union[int, float]

    keywords: SFXKeywords

    releases: SFXReleases

    # Time this sound effect was last updated
    updated_time: datetime

    url: str

class SFX(RequiredSFX, OptionalSFX):
    pass
