# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredVideoSizeDetails(TypedDict):
    pass

class OptionalVideoSizeDetails(TypedDict, total=False):
    # Display name of this video size
    display_name: str

    # File size (in bytes) of this video size
    file_size: int

    # Format of this video size
    format: str

    # Frames per second of this video size
    fps: typing.Union[int, float]

    # Height of this video size
    height: int

    # Whether or not videos can be licensed in this video size
    is_licensable: bool

    # Width of this video size
    width: int

class VideoSizeDetails(RequiredVideoSizeDetails, OptionalVideoSizeDetails):
    pass
