# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from shutterstock_python_sdk import schemas  # noqa: F401


class Allotment(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    An allotment of credits as part of a subscription
    """


    class MetaOapg:
        
        class properties:
            downloads_left = schemas.IntSchema
            downloads_limit = schemas.IntSchema
            end_time = schemas.DateTimeSchema
            start_time = schemas.DateTimeSchema
            __annotations__ = {
                "downloads_left": downloads_left,
                "downloads_limit": downloads_limit,
                "end_time": end_time,
                "start_time": start_time,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["downloads_left"]) -> MetaOapg.properties.downloads_left: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["downloads_limit"]) -> MetaOapg.properties.downloads_limit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["end_time"]) -> MetaOapg.properties.end_time: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["start_time"]) -> MetaOapg.properties.start_time: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["downloads_left", "downloads_limit", "end_time", "start_time", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["downloads_left"]) -> typing.Union[MetaOapg.properties.downloads_left, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["downloads_limit"]) -> typing.Union[MetaOapg.properties.downloads_limit, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["end_time"]) -> typing.Union[MetaOapg.properties.end_time, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["start_time"]) -> typing.Union[MetaOapg.properties.start_time, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["downloads_left", "downloads_limit", "end_time", "start_time", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        downloads_left: typing.Union[MetaOapg.properties.downloads_left, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        downloads_limit: typing.Union[MetaOapg.properties.downloads_limit, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        end_time: typing.Union[MetaOapg.properties.end_time, str, datetime, schemas.Unset] = schemas.unset,
        start_time: typing.Union[MetaOapg.properties.start_time, str, datetime, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Allotment':
        return super().__new__(
            cls,
            *args,
            downloads_left=downloads_left,
            downloads_limit=downloads_limit,
            end_time=end_time,
            start_time=start_time,
            _configuration=_configuration,
            **kwargs,
        )
