# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from shutterstock_python_sdk import schemas  # noqa: F401


class AudioRenderTimelineSpanInstrumentGroup(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    An instrument and the status objects that specify when that instrument plays
    """


    class MetaOapg:
        required = {
            "instrument_group",
        }
        
        class properties:
            instrument_group = schemas.StrSchema
            
            
            class statuses(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['AudioRenderTimelineSpanInstrumentGroupStatus']:
                        return AudioRenderTimelineSpanInstrumentGroupStatus
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['AudioRenderTimelineSpanInstrumentGroupStatus'], typing.List['AudioRenderTimelineSpanInstrumentGroupStatus']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'statuses':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'AudioRenderTimelineSpanInstrumentGroupStatus':
                    return super().__getitem__(i)
            __annotations__ = {
                "instrument_group": instrument_group,
                "statuses": statuses,
            }
    
    instrument_group: MetaOapg.properties.instrument_group
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["instrument_group"]) -> MetaOapg.properties.instrument_group: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["statuses"]) -> MetaOapg.properties.statuses: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["instrument_group", "statuses", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["instrument_group"]) -> MetaOapg.properties.instrument_group: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["statuses"]) -> typing.Union[MetaOapg.properties.statuses, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["instrument_group", "statuses", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        instrument_group: typing.Union[MetaOapg.properties.instrument_group, str, ],
        statuses: typing.Union[MetaOapg.properties.statuses, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AudioRenderTimelineSpanInstrumentGroup':
        return super().__new__(
            cls,
            *args,
            instrument_group=instrument_group,
            statuses=statuses,
            _configuration=_configuration,
            **kwargs,
        )

from shutterstock_python_sdk.model.audio_render_timeline_span_instrument_group_status import AudioRenderTimelineSpanInstrumentGroupStatus
