# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from shutterstock_python_sdk import schemas  # noqa: F401


class AudioRenderTimelineSpanRegionEndType(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    A high-level description of how a region ends
    """


    class MetaOapg:
        required = {
            "beat",
            "event",
            "type",
        }
        
        class properties:
            beat = schemas.NumberSchema
            
            
            class event(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "ending": "ENDING",
                        "transition": "TRANSITION",
                    }
                
                @schemas.classproperty
                def ENDING(cls):
                    return cls("ending")
                
                @schemas.classproperty
                def TRANSITION(cls):
                    return cls("transition")
            
            
            class type(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "ringout": "RINGOUT",
                        "cut": "CUT",
                    }
                
                @schemas.classproperty
                def RINGOUT(cls):
                    return cls("ringout")
                
                @schemas.classproperty
                def CUT(cls):
                    return cls("cut")
            __annotations__ = {
                "beat": beat,
                "event": event,
                "type": type,
            }
    
    beat: MetaOapg.properties.beat
    event: MetaOapg.properties.event
    type: MetaOapg.properties.type
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["beat"]) -> MetaOapg.properties.beat: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["event"]) -> MetaOapg.properties.event: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["beat", "event", "type", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["beat"]) -> MetaOapg.properties.beat: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["event"]) -> MetaOapg.properties.event: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["beat", "event", "type", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        beat: typing.Union[MetaOapg.properties.beat, decimal.Decimal, int, float, ],
        event: typing.Union[MetaOapg.properties.event, str, ],
        type: typing.Union[MetaOapg.properties.type, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AudioRenderTimelineSpanRegionEndType':
        return super().__new__(
            cls,
            *args,
            beat=beat,
            event=event,
            type=type,
            _configuration=_configuration,
            **kwargs,
        )
