# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from shutterstock_python_sdk import schemas  # noqa: F401


class CatalogCollectionItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Metadata about an item that is part of a collection
    """


    class MetaOapg:
        required = {
            "created_time",
            "id",
            "asset",
        }
        
        class properties:
        
            @staticmethod
            def asset() -> typing.Type['CatalogCollectionItemAsset']:
                return CatalogCollectionItemAsset
            created_time = schemas.DateTimeSchema
            id = schemas.StrSchema
        
            @staticmethod
            def collection_ids() -> typing.Type['CatalogCollectionItemCollectionIds']:
                return CatalogCollectionItemCollectionIds
            __annotations__ = {
                "asset": asset,
                "created_time": created_time,
                "id": id,
                "collection_ids": collection_ids,
            }
    
    created_time: MetaOapg.properties.created_time
    id: MetaOapg.properties.id
    asset: 'CatalogCollectionItemAsset'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["asset"]) -> 'CatalogCollectionItemAsset': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["created_time"]) -> MetaOapg.properties.created_time: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["collection_ids"]) -> 'CatalogCollectionItemCollectionIds': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["asset", "created_time", "id", "collection_ids", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["asset"]) -> 'CatalogCollectionItemAsset': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["created_time"]) -> MetaOapg.properties.created_time: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["collection_ids"]) -> typing.Union['CatalogCollectionItemCollectionIds', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["asset", "created_time", "id", "collection_ids", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        created_time: typing.Union[MetaOapg.properties.created_time, str, datetime, ],
        id: typing.Union[MetaOapg.properties.id, str, ],
        asset: 'CatalogCollectionItemAsset',
        collection_ids: typing.Union['CatalogCollectionItemCollectionIds', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CatalogCollectionItem':
        return super().__new__(
            cls,
            *args,
            created_time=created_time,
            id=id,
            asset=asset,
            collection_ids=collection_ids,
            _configuration=_configuration,
            **kwargs,
        )

from shutterstock_python_sdk.model.catalog_collection_item_asset import CatalogCollectionItemAsset
from shutterstock_python_sdk.model.catalog_collection_item_collection_ids import CatalogCollectionItemCollectionIds
