# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from shutterstock_python_sdk import schemas  # noqa: F401


class CatalogCollectionRoleAssignments(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    List of role assignments for a catalog collection
    """


    class MetaOapg:
        required = {
            "collection_id",
            "roles",
        }
        
        class properties:
            collection_id = schemas.StrSchema
        
            @staticmethod
            def roles() -> typing.Type['CatalogCollectionRoleAssignmentsRoles']:
                return CatalogCollectionRoleAssignmentsRoles
            __annotations__ = {
                "collection_id": collection_id,
                "roles": roles,
            }
    
    collection_id: MetaOapg.properties.collection_id
    roles: 'CatalogCollectionRoleAssignmentsRoles'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["collection_id"]) -> MetaOapg.properties.collection_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["roles"]) -> 'CatalogCollectionRoleAssignmentsRoles': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["collection_id", "roles", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["collection_id"]) -> MetaOapg.properties.collection_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["roles"]) -> 'CatalogCollectionRoleAssignmentsRoles': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["collection_id", "roles", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        collection_id: typing.Union[MetaOapg.properties.collection_id, str, ],
        roles: 'CatalogCollectionRoleAssignmentsRoles',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CatalogCollectionRoleAssignments':
        return super().__new__(
            cls,
            *args,
            collection_id=collection_id,
            roles=roles,
            _configuration=_configuration,
            **kwargs,
        )

from shutterstock_python_sdk.model.catalog_collection_role_assignments_roles import CatalogCollectionRoleAssignmentsRoles
