# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from shutterstock_python_sdk import schemas  # noqa: F401


class DownloadHistoryRevshareDetails(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Pricing information for revenue-sharing transactions
    """


    class MetaOapg:
        required = {
            "purchase_amount",
            "purchase_currency",
        }
        
        class properties:
            purchase_amount = schemas.StrSchema
            purchase_currency = schemas.StrSchema
            __annotations__ = {
                "purchase_amount": purchase_amount,
                "purchase_currency": purchase_currency,
            }
    
    purchase_amount: MetaOapg.properties.purchase_amount
    purchase_currency: MetaOapg.properties.purchase_currency
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["purchase_amount"]) -> MetaOapg.properties.purchase_amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["purchase_currency"]) -> MetaOapg.properties.purchase_currency: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["purchase_amount", "purchase_currency", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["purchase_amount"]) -> MetaOapg.properties.purchase_amount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["purchase_currency"]) -> MetaOapg.properties.purchase_currency: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["purchase_amount", "purchase_currency", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        purchase_amount: typing.Union[MetaOapg.properties.purchase_amount, str, ],
        purchase_currency: typing.Union[MetaOapg.properties.purchase_currency, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DownloadHistoryRevshareDetails':
        return super().__new__(
            cls,
            *args,
            purchase_amount=purchase_amount,
            purchase_currency=purchase_currency,
            _configuration=_configuration,
            **kwargs,
        )
