# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from shutterstock_python_sdk import schemas  # noqa: F401


class EditorialVideoAssets(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Asset information, including size and thumbnail URLs
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def original() -> typing.Type['VideoSizeDetails']:
                return VideoSizeDetails
        
            @staticmethod
            def preview_mp4() -> typing.Type['VideoPreviewUrl']:
                return VideoPreviewUrl
        
            @staticmethod
            def preview_webm() -> typing.Type['VideoPreviewUrl']:
                return VideoPreviewUrl
        
            @staticmethod
            def thumb_jpg() -> typing.Type['VideoPreviewUrl']:
                return VideoPreviewUrl
            __annotations__ = {
                "original": original,
                "preview_mp4": preview_mp4,
                "preview_webm": preview_webm,
                "thumb_jpg": thumb_jpg,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["original"]) -> 'VideoSizeDetails': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["preview_mp4"]) -> 'VideoPreviewUrl': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["preview_webm"]) -> 'VideoPreviewUrl': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["thumb_jpg"]) -> 'VideoPreviewUrl': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["original", "preview_mp4", "preview_webm", "thumb_jpg", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["original"]) -> typing.Union['VideoSizeDetails', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["preview_mp4"]) -> typing.Union['VideoPreviewUrl', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["preview_webm"]) -> typing.Union['VideoPreviewUrl', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["thumb_jpg"]) -> typing.Union['VideoPreviewUrl', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["original", "preview_mp4", "preview_webm", "thumb_jpg", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        original: typing.Union['VideoSizeDetails', schemas.Unset] = schemas.unset,
        preview_mp4: typing.Union['VideoPreviewUrl', schemas.Unset] = schemas.unset,
        preview_webm: typing.Union['VideoPreviewUrl', schemas.Unset] = schemas.unset,
        thumb_jpg: typing.Union['VideoPreviewUrl', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'EditorialVideoAssets':
        return super().__new__(
            cls,
            *args,
            original=original,
            preview_mp4=preview_mp4,
            preview_webm=preview_webm,
            thumb_jpg=thumb_jpg,
            _configuration=_configuration,
            **kwargs,
        )

from shutterstock_python_sdk.model.video_preview_url import VideoPreviewUrl
from shutterstock_python_sdk.model.video_size_details import VideoSizeDetails
