# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from shutterstock_python_sdk import schemas  # noqa: F401


class EditorialVideoContent(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Metadata about editorial content
    """


    class MetaOapg:
        required = {
            "id",
        }
        
        class properties:
            id = schemas.StrSchema
            title = schemas.StrSchema
            description = schemas.StrSchema
            aspect = schemas.NumberSchema
        
            @staticmethod
            def assets() -> typing.Type['EditorialVideoAssets']:
                return EditorialVideoAssets
            byline = schemas.StrSchema
            caption = schemas.StrSchema
            
            
            class categories(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['EditorialCategory']:
                        return EditorialCategory
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['EditorialCategory'], typing.List['EditorialCategory']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'categories':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'EditorialCategory':
                    return super().__getitem__(i)
            date_taken = schemas.DateSchema
        
            @staticmethod
            def keywords() -> typing.Type['EditorialVideoContentKeywords']:
                return EditorialVideoContentKeywords
            __annotations__ = {
                "id": id,
                "title": title,
                "description": description,
                "aspect": aspect,
                "assets": assets,
                "byline": byline,
                "caption": caption,
                "categories": categories,
                "date_taken": date_taken,
                "keywords": keywords,
            }
    
    id: MetaOapg.properties.id
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["aspect"]) -> MetaOapg.properties.aspect: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assets"]) -> 'EditorialVideoAssets': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["byline"]) -> MetaOapg.properties.byline: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["caption"]) -> MetaOapg.properties.caption: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["categories"]) -> MetaOapg.properties.categories: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["date_taken"]) -> MetaOapg.properties.date_taken: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["keywords"]) -> 'EditorialVideoContentKeywords': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "title", "description", "aspect", "assets", "byline", "caption", "categories", "date_taken", "keywords", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["title"]) -> typing.Union[MetaOapg.properties.title, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["aspect"]) -> typing.Union[MetaOapg.properties.aspect, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assets"]) -> typing.Union['EditorialVideoAssets', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["byline"]) -> typing.Union[MetaOapg.properties.byline, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["caption"]) -> typing.Union[MetaOapg.properties.caption, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["categories"]) -> typing.Union[MetaOapg.properties.categories, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["date_taken"]) -> typing.Union[MetaOapg.properties.date_taken, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["keywords"]) -> typing.Union['EditorialVideoContentKeywords', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "title", "description", "aspect", "assets", "byline", "caption", "categories", "date_taken", "keywords", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        id: typing.Union[MetaOapg.properties.id, str, ],
        title: typing.Union[MetaOapg.properties.title, str, schemas.Unset] = schemas.unset,
        description: typing.Union[MetaOapg.properties.description, str, schemas.Unset] = schemas.unset,
        aspect: typing.Union[MetaOapg.properties.aspect, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        assets: typing.Union['EditorialVideoAssets', schemas.Unset] = schemas.unset,
        byline: typing.Union[MetaOapg.properties.byline, str, schemas.Unset] = schemas.unset,
        caption: typing.Union[MetaOapg.properties.caption, str, schemas.Unset] = schemas.unset,
        categories: typing.Union[MetaOapg.properties.categories, list, tuple, schemas.Unset] = schemas.unset,
        date_taken: typing.Union[MetaOapg.properties.date_taken, str, date, schemas.Unset] = schemas.unset,
        keywords: typing.Union['EditorialVideoContentKeywords', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'EditorialVideoContent':
        return super().__new__(
            cls,
            *args,
            id=id,
            title=title,
            description=description,
            aspect=aspect,
            assets=assets,
            byline=byline,
            caption=caption,
            categories=categories,
            date_taken=date_taken,
            keywords=keywords,
            _configuration=_configuration,
            **kwargs,
        )

from shutterstock_python_sdk.model.editorial_category import EditorialCategory
from shutterstock_python_sdk.model.editorial_video_assets import EditorialVideoAssets
from shutterstock_python_sdk.model.editorial_video_content_keywords import EditorialVideoContentKeywords
