# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from shutterstock_python_sdk import schemas  # noqa: F401


class EditorialUpdatedContent(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Metadata about updated editorial content
    """


    class MetaOapg:
        required = {
            "id",
        }
        
        class properties:
            id = schemas.StrSchema
            title = schemas.StrSchema
            description = schemas.StrSchema
            aspect = schemas.NumberSchema
        
            @staticmethod
            def assets() -> typing.Type['EditorialAssets']:
                return EditorialAssets
            byline = schemas.StrSchema
            caption = schemas.StrSchema
            
            
            class categories(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['EditorialCategory']:
                        return EditorialCategory
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['EditorialCategory'], typing.List['EditorialCategory']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'categories':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'EditorialCategory':
                    return super().__getitem__(i)
            
            
            class commercial_status(
                schemas.AnyTypeSchema,
            ):
            
            
                class MetaOapg:
                    
                    class properties:
                        reason = schemas.StrSchema
                        status = schemas.StrSchema
                        __annotations__ = {
                            "reason": reason,
                            "status": status,
                        }
            
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["reason"]) -> MetaOapg.properties.reason: ...
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
                
                @typing.overload
                def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                
                def __getitem__(self, name: typing.Union[typing_extensions.Literal["reason", "status", ], str]):
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["reason"]) -> typing.Union[MetaOapg.properties.reason, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                
                def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["reason", "status", ], str]):
                    return super().get_item_oapg(name)
                
            
                def __new__(
                    cls,
                    *args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                    reason: typing.Union[MetaOapg.properties.reason, str, schemas.Unset] = schemas.unset,
                    status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                ) -> 'commercial_status':
                    return super().__new__(
                        cls,
                        *args,
                        reason=reason,
                        status=status,
                        _configuration=_configuration,
                        **kwargs,
                    )
            created_time = schemas.DateTimeSchema
            date_taken = schemas.DateSchema
        
            @staticmethod
            def keywords() -> typing.Type['EditorialUpdatedContentKeywords']:
                return EditorialUpdatedContentKeywords
        
            @staticmethod
            def rights() -> typing.Type['EditorialUpdatedContentRights']:
                return EditorialUpdatedContentRights
            special_instructions = schemas.StrSchema
            supplier_code = schemas.StrSchema
            updated_time = schemas.DateTimeSchema
        
            @staticmethod
            def updates() -> typing.Type['EditorialUpdatedContentUpdates']:
                return EditorialUpdatedContentUpdates
            __annotations__ = {
                "id": id,
                "title": title,
                "description": description,
                "aspect": aspect,
                "assets": assets,
                "byline": byline,
                "caption": caption,
                "categories": categories,
                "commercial_status": commercial_status,
                "created_time": created_time,
                "date_taken": date_taken,
                "keywords": keywords,
                "rights": rights,
                "special_instructions": special_instructions,
                "supplier_code": supplier_code,
                "updated_time": updated_time,
                "updates": updates,
            }
    
    id: MetaOapg.properties.id
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["aspect"]) -> MetaOapg.properties.aspect: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assets"]) -> 'EditorialAssets': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["byline"]) -> MetaOapg.properties.byline: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["caption"]) -> MetaOapg.properties.caption: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["categories"]) -> MetaOapg.properties.categories: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["commercial_status"]) -> MetaOapg.properties.commercial_status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["created_time"]) -> MetaOapg.properties.created_time: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["date_taken"]) -> MetaOapg.properties.date_taken: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["keywords"]) -> 'EditorialUpdatedContentKeywords': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rights"]) -> 'EditorialUpdatedContentRights': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["special_instructions"]) -> MetaOapg.properties.special_instructions: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["supplier_code"]) -> MetaOapg.properties.supplier_code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updated_time"]) -> MetaOapg.properties.updated_time: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updates"]) -> 'EditorialUpdatedContentUpdates': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "title", "description", "aspect", "assets", "byline", "caption", "categories", "commercial_status", "created_time", "date_taken", "keywords", "rights", "special_instructions", "supplier_code", "updated_time", "updates", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["title"]) -> typing.Union[MetaOapg.properties.title, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["aspect"]) -> typing.Union[MetaOapg.properties.aspect, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assets"]) -> typing.Union['EditorialAssets', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["byline"]) -> typing.Union[MetaOapg.properties.byline, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["caption"]) -> typing.Union[MetaOapg.properties.caption, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["categories"]) -> typing.Union[MetaOapg.properties.categories, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["commercial_status"]) -> typing.Union[MetaOapg.properties.commercial_status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["created_time"]) -> typing.Union[MetaOapg.properties.created_time, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["date_taken"]) -> typing.Union[MetaOapg.properties.date_taken, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["keywords"]) -> typing.Union['EditorialUpdatedContentKeywords', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rights"]) -> typing.Union['EditorialUpdatedContentRights', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["special_instructions"]) -> typing.Union[MetaOapg.properties.special_instructions, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["supplier_code"]) -> typing.Union[MetaOapg.properties.supplier_code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updated_time"]) -> typing.Union[MetaOapg.properties.updated_time, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updates"]) -> typing.Union['EditorialUpdatedContentUpdates', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "title", "description", "aspect", "assets", "byline", "caption", "categories", "commercial_status", "created_time", "date_taken", "keywords", "rights", "special_instructions", "supplier_code", "updated_time", "updates", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        id: typing.Union[MetaOapg.properties.id, str, ],
        title: typing.Union[MetaOapg.properties.title, str, schemas.Unset] = schemas.unset,
        description: typing.Union[MetaOapg.properties.description, str, schemas.Unset] = schemas.unset,
        aspect: typing.Union[MetaOapg.properties.aspect, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        assets: typing.Union['EditorialAssets', schemas.Unset] = schemas.unset,
        byline: typing.Union[MetaOapg.properties.byline, str, schemas.Unset] = schemas.unset,
        caption: typing.Union[MetaOapg.properties.caption, str, schemas.Unset] = schemas.unset,
        categories: typing.Union[MetaOapg.properties.categories, list, tuple, schemas.Unset] = schemas.unset,
        commercial_status: typing.Union[MetaOapg.properties.commercial_status, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        created_time: typing.Union[MetaOapg.properties.created_time, str, datetime, schemas.Unset] = schemas.unset,
        date_taken: typing.Union[MetaOapg.properties.date_taken, str, date, schemas.Unset] = schemas.unset,
        keywords: typing.Union['EditorialUpdatedContentKeywords', schemas.Unset] = schemas.unset,
        rights: typing.Union['EditorialUpdatedContentRights', schemas.Unset] = schemas.unset,
        special_instructions: typing.Union[MetaOapg.properties.special_instructions, str, schemas.Unset] = schemas.unset,
        supplier_code: typing.Union[MetaOapg.properties.supplier_code, str, schemas.Unset] = schemas.unset,
        updated_time: typing.Union[MetaOapg.properties.updated_time, str, datetime, schemas.Unset] = schemas.unset,
        updates: typing.Union['EditorialUpdatedContentUpdates', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'EditorialUpdatedContent':
        return super().__new__(
            cls,
            *args,
            id=id,
            title=title,
            description=description,
            aspect=aspect,
            assets=assets,
            byline=byline,
            caption=caption,
            categories=categories,
            commercial_status=commercial_status,
            created_time=created_time,
            date_taken=date_taken,
            keywords=keywords,
            rights=rights,
            special_instructions=special_instructions,
            supplier_code=supplier_code,
            updated_time=updated_time,
            updates=updates,
            _configuration=_configuration,
            **kwargs,
        )

from shutterstock_python_sdk.model.editorial_assets import EditorialAssets
from shutterstock_python_sdk.model.editorial_category import EditorialCategory
from shutterstock_python_sdk.model.editorial_updated_content_keywords import EditorialUpdatedContentKeywords
from shutterstock_python_sdk.model.editorial_updated_content_rights import EditorialUpdatedContentRights
from shutterstock_python_sdk.model.editorial_updated_content_updates import EditorialUpdatedContentUpdates
