# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from shutterstock_python_sdk import schemas  # noqa: F401


class LicenseAudioRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Audio license request data
    """


    class MetaOapg:
        required = {
            "audio",
        }
        
        class properties:
            
            
            class audio(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['LicenseAudio']:
                        return LicenseAudio
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['LicenseAudio'], typing.List['LicenseAudio']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'audio':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'LicenseAudio':
                    return super().__getitem__(i)
            __annotations__ = {
                "audio": audio,
            }
    
    audio: MetaOapg.properties.audio
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["audio"]) -> MetaOapg.properties.audio: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["audio", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["audio"]) -> MetaOapg.properties.audio: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["audio", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        audio: typing.Union[MetaOapg.properties.audio, list, tuple, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'LicenseAudioRequest':
        return super().__new__(
            cls,
            *args,
            audio=audio,
            _configuration=_configuration,
            **kwargs,
        )

from shutterstock_python_sdk.model.license_audio import LicenseAudio
