# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from shutterstock_python_sdk import schemas  # noqa: F401


class LicenseAudio(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    An audio track in a licensing request
    """


    class MetaOapg:
        required = {
            "audio_id",
        }
        
        class properties:
            audio_id = schemas.StrSchema
            
            
            class license(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "audio_platform": "AUDIO_PLATFORM",
                        "premier_music_basic": "PREMIER_MUSIC_BASIC",
                        "premier_music_extended": "PREMIER_MUSIC_EXTENDED",
                        "premier_music_pro": "PREMIER_MUSIC_PRO",
                        "premier_music_comp": "PREMIER_MUSIC_COMP",
                        "asset_all_music": "ASSET_ALL_MUSIC",
                    }
                
                @schemas.classproperty
                def AUDIO_PLATFORM(cls):
                    return cls("audio_platform")
                
                @schemas.classproperty
                def PREMIER_MUSIC_BASIC(cls):
                    return cls("premier_music_basic")
                
                @schemas.classproperty
                def PREMIER_MUSIC_EXTENDED(cls):
                    return cls("premier_music_extended")
                
                @schemas.classproperty
                def PREMIER_MUSIC_PRO(cls):
                    return cls("premier_music_pro")
                
                @schemas.classproperty
                def PREMIER_MUSIC_COMP(cls):
                    return cls("premier_music_comp")
                
                @schemas.classproperty
                def ASSET_ALL_MUSIC(cls):
                    return cls("asset_all_music")
            search_id = schemas.StrSchema
            __annotations__ = {
                "audio_id": audio_id,
                "license": license,
                "search_id": search_id,
            }
    
    audio_id: MetaOapg.properties.audio_id
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["audio_id"]) -> MetaOapg.properties.audio_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["license"]) -> MetaOapg.properties.license: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["search_id"]) -> MetaOapg.properties.search_id: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["audio_id", "license", "search_id", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["audio_id"]) -> MetaOapg.properties.audio_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["license"]) -> typing.Union[MetaOapg.properties.license, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["search_id"]) -> typing.Union[MetaOapg.properties.search_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["audio_id", "license", "search_id", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        audio_id: typing.Union[MetaOapg.properties.audio_id, str, ],
        license: typing.Union[MetaOapg.properties.license, str, schemas.Unset] = schemas.unset,
        search_id: typing.Union[MetaOapg.properties.search_id, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'LicenseAudio':
        return super().__new__(
            cls,
            *args,
            audio_id=audio_id,
            license=license,
            search_id=search_id,
            _configuration=_configuration,
            **kwargs,
        )
