# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from shutterstock_python_sdk import schemas  # noqa: F401


class UserDetails(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    User details
    """


    class MetaOapg:
        
        class properties:
            contributor_id = schemas.StrSchema
            customer_id = schemas.StrSchema
            email = schemas.StrSchema
            first_name = schemas.StrSchema
            full_name = schemas.StrSchema
            id = schemas.StrSchema
            is_premier = schemas.BoolSchema
            is_premier_parent = schemas.BoolSchema
            language = schemas.StrSchema
            last_name = schemas.StrSchema
            only_enhanced_license = schemas.BoolSchema
            only_sensitive_use = schemas.BoolSchema
            organization_id = schemas.StrSchema
        
            @staticmethod
            def premier_permissions() -> typing.Type['UserDetailsPremierPermissions']:
                return UserDetailsPremierPermissions
            username = schemas.StrSchema
            __annotations__ = {
                "contributor_id": contributor_id,
                "customer_id": customer_id,
                "email": email,
                "first_name": first_name,
                "full_name": full_name,
                "id": id,
                "is_premier": is_premier,
                "is_premier_parent": is_premier_parent,
                "language": language,
                "last_name": last_name,
                "only_enhanced_license": only_enhanced_license,
                "only_sensitive_use": only_sensitive_use,
                "organization_id": organization_id,
                "premier_permissions": premier_permissions,
                "username": username,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["contributor_id"]) -> MetaOapg.properties.contributor_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["customer_id"]) -> MetaOapg.properties.customer_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["email"]) -> MetaOapg.properties.email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["first_name"]) -> MetaOapg.properties.first_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["full_name"]) -> MetaOapg.properties.full_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_premier"]) -> MetaOapg.properties.is_premier: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_premier_parent"]) -> MetaOapg.properties.is_premier_parent: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["language"]) -> MetaOapg.properties.language: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["last_name"]) -> MetaOapg.properties.last_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["only_enhanced_license"]) -> MetaOapg.properties.only_enhanced_license: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["only_sensitive_use"]) -> MetaOapg.properties.only_sensitive_use: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["organization_id"]) -> MetaOapg.properties.organization_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["premier_permissions"]) -> 'UserDetailsPremierPermissions': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["username"]) -> MetaOapg.properties.username: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["contributor_id", "customer_id", "email", "first_name", "full_name", "id", "is_premier", "is_premier_parent", "language", "last_name", "only_enhanced_license", "only_sensitive_use", "organization_id", "premier_permissions", "username", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["contributor_id"]) -> typing.Union[MetaOapg.properties.contributor_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["customer_id"]) -> typing.Union[MetaOapg.properties.customer_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["email"]) -> typing.Union[MetaOapg.properties.email, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["first_name"]) -> typing.Union[MetaOapg.properties.first_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["full_name"]) -> typing.Union[MetaOapg.properties.full_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_premier"]) -> typing.Union[MetaOapg.properties.is_premier, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_premier_parent"]) -> typing.Union[MetaOapg.properties.is_premier_parent, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["language"]) -> typing.Union[MetaOapg.properties.language, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["last_name"]) -> typing.Union[MetaOapg.properties.last_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["only_enhanced_license"]) -> typing.Union[MetaOapg.properties.only_enhanced_license, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["only_sensitive_use"]) -> typing.Union[MetaOapg.properties.only_sensitive_use, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["organization_id"]) -> typing.Union[MetaOapg.properties.organization_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["premier_permissions"]) -> typing.Union['UserDetailsPremierPermissions', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["username"]) -> typing.Union[MetaOapg.properties.username, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["contributor_id", "customer_id", "email", "first_name", "full_name", "id", "is_premier", "is_premier_parent", "language", "last_name", "only_enhanced_license", "only_sensitive_use", "organization_id", "premier_permissions", "username", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        contributor_id: typing.Union[MetaOapg.properties.contributor_id, str, schemas.Unset] = schemas.unset,
        customer_id: typing.Union[MetaOapg.properties.customer_id, str, schemas.Unset] = schemas.unset,
        email: typing.Union[MetaOapg.properties.email, str, schemas.Unset] = schemas.unset,
        first_name: typing.Union[MetaOapg.properties.first_name, str, schemas.Unset] = schemas.unset,
        full_name: typing.Union[MetaOapg.properties.full_name, str, schemas.Unset] = schemas.unset,
        id: typing.Union[MetaOapg.properties.id, str, schemas.Unset] = schemas.unset,
        is_premier: typing.Union[MetaOapg.properties.is_premier, bool, schemas.Unset] = schemas.unset,
        is_premier_parent: typing.Union[MetaOapg.properties.is_premier_parent, bool, schemas.Unset] = schemas.unset,
        language: typing.Union[MetaOapg.properties.language, str, schemas.Unset] = schemas.unset,
        last_name: typing.Union[MetaOapg.properties.last_name, str, schemas.Unset] = schemas.unset,
        only_enhanced_license: typing.Union[MetaOapg.properties.only_enhanced_license, bool, schemas.Unset] = schemas.unset,
        only_sensitive_use: typing.Union[MetaOapg.properties.only_sensitive_use, bool, schemas.Unset] = schemas.unset,
        organization_id: typing.Union[MetaOapg.properties.organization_id, str, schemas.Unset] = schemas.unset,
        premier_permissions: typing.Union['UserDetailsPremierPermissions', schemas.Unset] = schemas.unset,
        username: typing.Union[MetaOapg.properties.username, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UserDetails':
        return super().__new__(
            cls,
            *args,
            contributor_id=contributor_id,
            customer_id=customer_id,
            email=email,
            first_name=first_name,
            full_name=full_name,
            id=id,
            is_premier=is_premier,
            is_premier_parent=is_premier_parent,
            language=language,
            last_name=last_name,
            only_enhanced_license=only_enhanced_license,
            only_sensitive_use=only_sensitive_use,
            organization_id=organization_id,
            premier_permissions=premier_permissions,
            username=username,
            _configuration=_configuration,
            **kwargs,
        )

from shutterstock_python_sdk.model.user_details_premier_permissions import UserDetailsPremierPermissions
