# coding: utf-8
"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from shutterstock_python_sdk.client_custom import ClientCustom
from shutterstock_python_sdk.configuration import Configuration
from shutterstock_python_sdk.api_client import ApiClient
from shutterstock_python_sdk.type_util import copy_signature
from shutterstock_python_sdk.apis.tags.audio_api import AudioApi
from shutterstock_python_sdk.apis.tags.catalog_api import CatalogApi
from shutterstock_python_sdk.apis.tags.computer_vision_api import ComputerVisionApi
from shutterstock_python_sdk.apis.tags.contributors_api import ContributorsApi
from shutterstock_python_sdk.apis.tags.custom_music_api import CustomMusicApi
from shutterstock_python_sdk.apis.tags.editorial_images_api import EditorialImagesApi
from shutterstock_python_sdk.apis.tags.editorial_video_api import EditorialVideoApi
from shutterstock_python_sdk.apis.tags.images_api import ImagesApi
from shutterstock_python_sdk.apis.tags.oauth_api import OauthApi
from shutterstock_python_sdk.apis.tags.sound_effects_api import SoundEffectsApi
from shutterstock_python_sdk.apis.tags.test_api import TestApi
from shutterstock_python_sdk.apis.tags.users_api import UsersApi
from shutterstock_python_sdk.apis.tags.videos_api import VideosApi



class Shutterstock(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.audio: AudioApi = AudioApi(api_client)
        self.catalog: CatalogApi = CatalogApi(api_client)
        self.computer_vision: ComputerVisionApi = ComputerVisionApi(api_client)
        self.contributors: ContributorsApi = ContributorsApi(api_client)
        self.custom_music: CustomMusicApi = CustomMusicApi(api_client)
        self.editorial_images: EditorialImagesApi = EditorialImagesApi(api_client)
        self.editorial_video: EditorialVideoApi = EditorialVideoApi(api_client)
        self.images: ImagesApi = ImagesApi(api_client)
        self.oauth: OauthApi = OauthApi(api_client)
        self.sound_effects: SoundEffectsApi = SoundEffectsApi(api_client)
        self.test: TestApi = TestApi(api_client)
        self.users: UsersApi = UsersApi(api_client)
        self.videos: VideosApi = VideosApi(api_client)
