# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from shutterstock_python_sdk.pydantic.album import Album
from shutterstock_python_sdk.pydantic.artist import Artist
from shutterstock_python_sdk.pydantic.audio_assets import AudioAssets
from shutterstock_python_sdk.pydantic.audio_genres import AudioGenres
from shutterstock_python_sdk.pydantic.audio_instruments import AudioInstruments
from shutterstock_python_sdk.pydantic.audio_keywords import AudioKeywords
from shutterstock_python_sdk.pydantic.audio_moods import AudioMoods
from shutterstock_python_sdk.pydantic.audio_releases import AudioReleases
from shutterstock_python_sdk.pydantic.contributor import Contributor
from shutterstock_python_sdk.pydantic.model_release import ModelRelease

class Audio(BaseModel):
    contributor: Contributor = Field(alias='contributor')

    # Shutterstock ID of this track
    id: str = Field(alias='id')

    # Media type of this track; should always be \"audio\"
    media_type: str = Field(alias='media_type')

    # Title of this track
    title: typing.Optional[str] = Field(None, alias='title')

    # Description of this track
    description: typing.Optional[str] = Field(None, alias='description')

    # Date this track was added to the Shutterstock library
    added_date: typing.Optional[date] = Field(None, alias='added_date')

    # Affiliate referral link; appears only for registered affiliate partners
    affiliate_url: typing.Optional[str] = Field(None, alias='affiliate_url')

    album: typing.Optional[Album] = Field(None, alias='album')

    # List of artists
    artists: typing.Optional[typing.List[Artist]] = Field(None, alias='artists')

    assets: typing.Optional[AudioAssets] = Field(None, alias='assets')

    # BPM (beats per minute) of this track
    bpm: typing.Optional[int] = Field(None, alias='bpm')

    deleted_time: typing.Optional[datetime] = Field(None, alias='deleted_time')

    # Duration of this track in seconds
    duration: typing.Optional[typing.Union[int, float]] = Field(None, alias='duration')

    genres: typing.Optional[AudioGenres] = Field(None, alias='genres')

    instruments: typing.Optional[AudioInstruments] = Field(None, alias='instruments')

    # Whether or not this track contains adult content
    is_adult: typing.Optional[bool] = Field(None, alias='is_adult')

    # Whether or not this track is purely instrumental (lacking lyrics)
    is_instrumental: typing.Optional[bool] = Field(None, alias='is_instrumental')

    isrc: typing.Optional[str] = Field(None, alias='isrc')

    keywords: typing.Optional[AudioKeywords] = Field(None, alias='keywords')

    # Language of this track's lyrics
    language: typing.Optional[str] = Field(None, alias='language')

    # Lyrics of this track
    lyrics: typing.Optional[str] = Field(None, alias='lyrics')

    # List of all model releases for this track
    model_releases_: typing.Optional[typing.List[ModelRelease]] = Field(None, alias='model_releases')

    moods: typing.Optional[AudioMoods] = Field(None, alias='moods')

    # Time this track was published
    published_time: typing.Optional[datetime] = Field(None, alias='published_time')

    # Recording version of this track
    recording_version: typing.Optional[str] = Field(None, alias='recording_version')

    releases: typing.Optional[AudioReleases] = Field(None, alias='releases')

    # List of all similar artists of this track
    similar_artists: typing.Optional[typing.List[Artist]] = Field(None, alias='similar_artists')

    # Time this track was submitted
    submitted_time: typing.Optional[datetime] = Field(None, alias='submitted_time')

    # Time this track was last updated
    updated_time: typing.Optional[datetime] = Field(None, alias='updated_time')

    url: typing.Optional[str] = Field(None, alias='url')

    # Vocal description of this track
    vocal_description: typing.Optional[str] = Field(None, alias='vocal_description')
    class Config:
        arbitrary_types_allowed = True
