# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from shutterstock_python_sdk.pydantic.audio_render_timeline_span import AudioRenderTimelineSpan

class AudioRenderTimeline(BaseModel):
    # A span object that represents the beginning of a period of absolute time
    spans: typing.Optional[typing.List[AudioRenderTimelineSpan]] = Field(None, alias='spans')
    class Config:
        arbitrary_types_allowed = True
