# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class AudioRenderTimelineSpanInstrumentGroupStatus(BaseModel):
    # The beat, relative to the span, at which the status begins
    beat: typing.Union[int, float] = Field(alias='beat')

    # Whether the instrument is playing or not
    status: Literal["active", "inactive"] = Field(alias='status')
    class Config:
        arbitrary_types_allowed = True
