# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from shutterstock_python_sdk.pydantic.audio_asset_details import AudioAssetDetails
from shutterstock_python_sdk.pydantic.shorts_loops_stems import ShortsLoopsStems

class AudioAssets(BaseModel):
    album_art: typing.Optional[AudioAssetDetails] = Field(None, alias='album_art')

    clean_audio: typing.Optional[AudioAssetDetails] = Field(None, alias='clean_audio')

    original_audio: typing.Optional[AudioAssetDetails] = Field(None, alias='original_audio')

    preview_mp3: typing.Optional[AudioAssetDetails] = Field(None, alias='preview_mp3')

    preview_ogg: typing.Optional[AudioAssetDetails] = Field(None, alias='preview_ogg')

    shorts_loops_stems: typing.Optional[ShortsLoopsStems] = Field(None, alias='shorts_loops_stems')

    waveform: typing.Optional[AudioAssetDetails] = Field(None, alias='waveform')
    class Config:
        arbitrary_types_allowed = True
