# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from shutterstock_python_sdk.pydantic.category import Category
from shutterstock_python_sdk.pydantic.error import Error

class CategoryDataList(BaseModel):
    # Categories
    data: typing.Optional[typing.List[Category]] = Field(None, alias='data')

    # Error list; appears only if there was an error
    errors: typing.Optional[typing.List[Error]] = Field(None, alias='errors')

    # Server-generated message, if any
    message: typing.Optional[str] = Field(None, alias='message')

    # The current page of results
    page: typing.Optional[int] = Field(None, alias='page')

    # The number of results per page
    per_page: typing.Optional[int] = Field(None, alias='per_page')

    # The total number of results across all pages
    total_count: typing.Optional[int] = Field(None, alias='total_count')
    class Config:
        arbitrary_types_allowed = True
