# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from shutterstock_python_sdk.pydantic.audio_render_timeline import AudioRenderTimeline

class CreateAudioRender(BaseModel):
    # A user-specified file name suggestion; this file name becomes the filename property of the Content-Disposition header when the user downloads the rendered audio file
    filename: str = Field(alias='filename')

    # File format, such as MP3 file, combined WAV file, or individual track WAV files
    preset: Literal["MASTER_MP3", "MASTER_WAV", "STEMS_WAV"] = Field(alias='preset')

    timeline: AudioRenderTimeline = Field(alias='timeline')
    class Config:
        arbitrary_types_allowed = True
