# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from shutterstock_python_sdk.pydantic.video_preview_url import VideoPreviewUrl
from shutterstock_python_sdk.pydantic.video_size_details import VideoSizeDetails

class EditorialVideoAssets(BaseModel):
    original: typing.Optional[VideoSizeDetails] = Field(None, alias='original')

    preview_mp4: typing.Optional[VideoPreviewUrl] = Field(None, alias='preview_mp4')

    preview_webm: typing.Optional[VideoPreviewUrl] = Field(None, alias='preview_webm')

    thumb_jpg: typing.Optional[VideoPreviewUrl] = Field(None, alias='thumb_jpg')
    class Config:
        arbitrary_types_allowed = True
