# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from shutterstock_python_sdk.pydantic.image_size_details import ImageSizeDetails
from shutterstock_python_sdk.pydantic.thumbnail import Thumbnail

class ImageAssets(BaseModel):
    huge_jpg: typing.Optional[ImageSizeDetails] = Field(None, alias='huge_jpg')

    huge_thumb: typing.Optional[Thumbnail] = Field(None, alias='huge_thumb')

    large_thumb: typing.Optional[Thumbnail] = Field(None, alias='large_thumb')

    medium_jpg: typing.Optional[ImageSizeDetails] = Field(None, alias='medium_jpg')

    preview: typing.Optional[Thumbnail] = Field(None, alias='preview')

    preview_1000: typing.Optional[Thumbnail] = Field(None, alias='preview_1000')

    preview_1500: typing.Optional[Thumbnail] = Field(None, alias='preview_1500')

    small_jpg: typing.Optional[ImageSizeDetails] = Field(None, alias='small_jpg')

    small_thumb: typing.Optional[Thumbnail] = Field(None, alias='small_thumb')

    supersize_jpg: typing.Optional[ImageSizeDetails] = Field(None, alias='supersize_jpg')

    vector_eps: typing.Optional[ImageSizeDetails] = Field(None, alias='vector_eps')
    class Config:
        arbitrary_types_allowed = True
