# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class LicenseSFX(BaseModel):
    # ID of the sounds effect being licensed
    sfx_id: str = Field(alias='sfx_id')

    # ID of the subscription to use for the download.
    subscription_id: str = Field(alias='subscription_id')

    audio_layout: typing.Optional[Literal["ambisonic", "5.1", "stereo"]] = Field(None, alias='audio_layout')

    format: typing.Optional[Literal["wav", "mp3"]] = Field(None, alias='format')

    # ID of the search that led to this licensing event
    search_id: typing.Optional[str] = Field(None, alias='search_id')
    class Config:
        arbitrary_types_allowed = True
