# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from shutterstock_python_sdk.pydantic.cookie import Cookie
from shutterstock_python_sdk.pydantic.custom_size_dimensions import CustomSizeDimensions
from shutterstock_python_sdk.pydantic.license_request_metadata import LicenseRequestMetadata

class LicenseImage(BaseModel):
    # Image ID
    image_id: str = Field(alias='image_id')

    auth_cookie: typing.Optional[Cookie] = Field(None, alias='auth_cookie')

    custom_dimensions: typing.Optional[CustomSizeDimensions] = Field(None, alias='custom_dimensions')

    # Set to true to acknowledge the editorial agreement
    editorial_acknowledgement: typing.Optional[bool] = Field(None, alias='editorial_acknowledgement')

    # (Deprecated) Image format to download
    format: typing.Optional[Literal["jpg"]] = Field(None, alias='format')

    metadata: typing.Optional[LicenseRequestMetadata] = Field(None, alias='metadata')

    # For revenue-sharing transactions, the final cost to the end customer as a floating-point number in the transaction currency, such as 12.34
    price: typing.Optional[typing.Union[int, float]] = Field(None, alias='price')

    # ID of the search that led to this licensing transaction
    search_id: typing.Optional[str] = Field(None, alias='search_id')

    # (Deprecated)
    show_modal: typing.Optional[bool] = Field(None, alias='show_modal')

    # Image size to download
    size: typing.Optional[Literal["small", "medium", "huge", "custom"]] = Field(None, alias='size')

    # ID of the subscription to use for the download.
    subscription_id: typing.Optional[str] = Field(None, alias='subscription_id')

    # (Deprecated)
    verification_code: typing.Optional[str] = Field(None, alias='verification_code')
    class Config:
        arbitrary_types_allowed = True
