# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

    The version of the OpenAPI document: 1.1.32
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from shutterstock_python_sdk.pydantic.cookie import Cookie

class RedownloadImage(BaseModel):
    auth_cookie: typing.Optional[Cookie] = Field(None, alias='auth_cookie')

    # (Deprecated)
    show_modal: typing.Optional[bool] = Field(None, alias='show_modal')

    # Size of the image
    size: typing.Optional[Literal["small", "medium", "huge", "supersize", "vector"]] = Field(None, alias='size')

    # (Deprecated)
    verification_code: typing.Optional[str] = Field(None, alias='verification_code')
    class Config:
        arbitrary_types_allowed = True
